POST http://localhost:3001/api/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdUBqZWEubm91IiwibmFtZSI6IkFudG9uX3Rlc3QiLCJpZCI6IjVjZTY0ZjQyYTljYzBhMTQ4OGU5ODdlMCIsImFkbWluIjpmYWxzZSwiaWF0IjoxNTU4NjAwMzc4fQ.qTbAl3VwJQkHhTFoAtfHmr6QmmdbudeZw0WsxMIWwy8

{
  "masseusse_id":"5cde7fa4011a6a288584abca",
  "user_id": "5ce64f42a9cc0a1488e987e0"
}
