POST https://limitless-wildwood-82265.herokuapp.com/api/users
Content-Type: application/json

{
  "name": "THIRD_USER",
  "number": "9012930213",
  "email": "nou@jea.nou",
  "admin": false,
  "password": "testing"
}
